# https://aka.ms/yaml

trigger:
  branches:
    include: [ master ] # branch names which will trigger a build
  tags:
    include: [ v* ] # tag names which will trigger a build

pr:
  branches:
    include: [ master ] # branch names which will trigger a build

pool:
  vmImage: 'ubuntu-latest'

variables:
  IMAGE_NAME: 'fibonacci_flask'

steps:
- task: Docker@2
  displayName: 'Build Image'
  inputs:
    command: 'build'
    Dockerfile: 'Dockerfile'
    tags: '$(IMAGE_NAME)'
    addPipelineData: false

- script: |
    if [ -f docker-compose.test.yaml ]; then
      docker-compose --file docker-compose.test.yaml run sut
      exitcode=$?
      docker-compose --file docker-compose.test.yaml down
      exit $exitcode
    else
      echo "`docker-compose.test.yaml` not found, nothing to run."
    fi
  displayName: 'Run tests'


- script: |
    IMAGE_ID=docker.pkg.github.com/$(Build.Repository.Name)/$(IMAGE_NAME)
          
    # Change all uppercase to lowercase
    IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
    # Strip git ref prefix from version
    VERSION=$(echo "$(Build.SourceBranch)" | sed -e 's,.*/\(.*\),\1,')
    # Strip "v" prefix from tag name
    [[ "$(Build.SourceBranch)" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
    # Use Docker `latest` tag convention
    [ "$VERSION" == "master" ] && VERSION=latest
  
    echo IMAGE_ID=${IMAGE_ID}
    echo VERSION=${VERSION}
    # Add new pipeline variables
    echo "##vso[task.setvariable variable=IMAGE_ID]${IMAGE_ID}"
    echo "##vso[task.setvariable variable=VERSION]${VERSION}"
    # tag docker image
    docker tag $(IMAGE_NAME) ${IMAGE_ID}:${VERSION}
  displayName: 'Tag Image'
    
- task: Docker@2
  inputs:
    containerRegistry: 'GithubDocker'
    repository: '$(IMAGE_ID)'
    command: 'push'
    tags: '$(VERSION)'
    addPipelineData: false
  displayName: 'Push Image'


