version: "3.8"
services:
  app:
    build: .
    image: fibonacci_flask
    expose:
      - "8080"
  
  sut:
    image: python:3.7-stretch
    environment:
      API_BASE_URL: http://app:8080
    command:
      - sh
      - -c
      - pip install -r /test/requirements.txt && pytest --disable-pytest-warnings /test
    depends_on:
      - app
    volumes:
      - "./tests/acceptance:/test"
    


